#!/bin/sh
MINGW_DIR=""
TLIB_DIR="lib/"
ENABLE_SHARED="YES"
SHARED_LIBRARY_EXT="so"
DATA_DIR=""
HOST=
HOST_PREF=""
CFLAGS_COMMON="${CFLAGS} -m32"
CFLAGS_SOURCE="-D_M_IX86 -DOPENAL_CONFIG=/bin/true"
CXXLAGS="${CXXLAGS} -m32"
LDFLAGS="${LDFLAGS} -m32 -L/usr/lib32 -L/usr/lib/i386-linux-gnu"
COMMAND_ENV="ARCH=i386"
