# cmake -DCMAKE_TOOLCHAIN_FILE=cmake/i386-linux-gnu.cmake -DCMAKE_FIND_ROOT_PATH=~/deb/temp -DCMAKE_C_FLAGS=-m32 -DCMAKE_CXX_FLAGS=-m32 .
set(CMAKE_SYSTEM_NAME "Linux")
set(CMAKE_SYSTEM_PROCESSOR "i386")