	CONFIG_KEY_NULL(),
	CONFIG_BLOCK_KEY(root, disable_cpu_exts),
	CONFIG_BLOCK_KEY(root, rt_prio),
	CONFIG_BLOCK_KEY(root, resampler),
	CONFIG_BLOCK_KEY(root, trap_al_error),
    CONFIG_BLOCK_KEY(root, trap_alc_error),
	CONFIG_BLOCK_KEY(root, drivers),
	CONFIG_BLOCK_KEY(root, default_reverb),
	CONFIG_BLOCK_KEY(root, sends),
	CONFIG_BLOCK_KEY(root, frequency),
	CONFIG_BLOCK_KEY(root, hrtf),
	CONFIG_BLOCK_KEY(root, wide_stereo), 
	CONFIG_BLOCK_KEY(root, channels),
	CONFIG_BLOCK_KEY(root, sample_type),
	CONFIG_BLOCK_KEY(root, periods),
    CONFIG_BLOCK_KEY(root, period_size),
    CONFIG_BLOCK_KEY(root, sources),
    CONFIG_BLOCK_KEY(root, slots),
    CONFIG_BLOCK_KEY(root, cf_level),
	CONFIG_BLOCK_KEY(root, hrtf_tables),
	CONFIG_BLOCK_KEY(root, layout),
	CONFIG_BLOCK_KEY(root, layout_stereo),
    CONFIG_BLOCK_KEY(root, layout_quad),
    CONFIG_BLOCK_KEY(root, layout_surround51),
    CONFIG_BLOCK_KEY(root, layout_side51),
    CONFIG_BLOCK_KEY(root, layout_surround61),
	CONFIG_BLOCK_KEY(root, layout_surround71),

	CONFIG_BLOCK_KEY(reverb, boost),
	CONFIG_BLOCK_KEY(reverb, emulate_eax),

	CONFIG_BLOCK_KEY(wave, file),