# Generated by CMake, DO NOT EDIT
/Users/elena/Documents/qfusion/libsrcs/libfreetype/CMakeFiles/cmake.check_cache: \
/Applications/CMake\ 2.8-12.app/Contents/share/cmake-2.8/Modules/CMakeCInformation.cmake\
/Applications/CMake\ 2.8-12.app/Contents/share/cmake-2.8/Modules/CMakeCXXInformation.cmake\
/Applications/CMake\ 2.8-12.app/Contents/share/cmake-2.8/Modules/CMakeCommonLanguageInclude.cmake\
/Applications/CMake\ 2.8-12.app/Contents/share/cmake-2.8/Modules/CMakeGenericSystem.cmake\
/Applications/CMake\ 2.8-12.app/Contents/share/cmake-2.8/Modules/CMakeSystemSpecificInformation.cmake\
/Applications/CMake\ 2.8-12.app/Contents/share/cmake-2.8/Modules/CPack.cmake\
/Applications/CMake\ 2.8-12.app/Contents/share/cmake-2.8/Modules/CPackComponent.cmake\
/Applications/CMake\ 2.8-12.app/Contents/share/cmake-2.8/Modules/Compiler/Clang-C.cmake\
/Applications/CMake\ 2.8-12.app/Contents/share/cmake-2.8/Modules/Compiler/Clang-CXX.cmake\
/Applications/CMake\ 2.8-12.app/Contents/share/cmake-2.8/Modules/Compiler/Clang.cmake\
/Applications/CMake\ 2.8-12.app/Contents/share/cmake-2.8/Modules/Compiler/GNU.cmake\
/Applications/CMake\ 2.8-12.app/Contents/share/cmake-2.8/Modules/Platform/Darwin-Clang-C.cmake\
/Applications/CMake\ 2.8-12.app/Contents/share/cmake-2.8/Modules/Platform/Darwin-Clang-CXX.cmake\
/Applications/CMake\ 2.8-12.app/Contents/share/cmake-2.8/Modules/Platform/Darwin-Clang.cmake\
/Applications/CMake\ 2.8-12.app/Contents/share/cmake-2.8/Modules/Platform/Darwin.cmake\
/Applications/CMake\ 2.8-12.app/Contents/share/cmake-2.8/Modules/Platform/UnixPaths.cmake\
/Applications/CMake\ 2.8-12.app/Contents/share/cmake-2.8/Templates/CPackConfig.cmake.in\
/Users/elena/Documents/qfusion/libsrcs/libfreetype/CMakeFiles/2.8.12.2/CMakeCCompiler.cmake\
/Users/elena/Documents/qfusion/libsrcs/libfreetype/CMakeFiles/2.8.12.2/CMakeCXXCompiler.cmake\
/Users/elena/Documents/qfusion/libsrcs/libfreetype/CMakeFiles/2.8.12.2/CMakeSystem.cmake\
/Users/elena/Documents/qfusion/libsrcs/libfreetype/CMakeLists.txt
	/Applications/CMake\ 2.8-12.app/Contents/bin/cmake -H/Users/elena/Documents/qfusion/libsrcs/libfreetype -B/Users/elena/Documents/qfusion/libsrcs/libfreetype
