name: Build

on:
  pull_request:
  push:
    branches: 
      - master
      - release/**

jobs:
  linux:
    strategy:
      matrix:
        config: [release, debug]
    uses: ./.github/workflows/linux-build.yml
    with:
      config: ${{ matrix.config }}
      cmake_args: "-DBUILD_UNIT_TEST=1"
    secrets: inherit
    
  macos:
    strategy:
      matrix:
        config: [release, debug]
    uses: ./.github/workflows/macos-build.yml
    with:
      config: ${{ matrix.config }}
      cmake_args: "-DBUILD_UNIT_TEST=1"
    secrets: inherit
    
  windows:
    strategy:
      matrix:
        config: [release, debug]
    uses: ./.github/workflows/windows-build.yml
    with:
      config: ${{ matrix.config }}
      cmake_args: "-DBUILD_UNIT_TEST=1"
    secrets: inherit

  test-linux:
    needs: linux
    runs-on: ubuntu-24.04
    container:
      image: registry.gitlab.steamos.cloud/steamrt/sniper/sdk:latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-x86_64-release
          path: drop

      - name: Extract artifact
        working-directory: ./drop
        run: tar -xzf linux-x86_64-release.tar.gz

      - name: Unit Test
        working-directory: ./drop
        shell: bash
        run: |
          set -e
          for exc in ./test/*; do
            chmod +x $exc
            $exc
          done

  test-macos:
    needs: macos
    runs-on: macos-14
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: osx-x86_64-release
          path: drop

      - name: Extract artifact
        working-directory: ./drop
        run: tar -xzf osx-x86_64-release.tar.gz

      - name: Unit Test
        working-directory: ./drop/RelWithDebInfo
        shell: bash
        run: |
          set -e
          for exc in ./test/*[^.dSYM]; do
            chmod +x $exc
            $exc
          done

  test-windows:
    needs: windows
    runs-on: windows-2022
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: win-x86_64-release
          path: drop

      - name: Extract artifact
        working-directory: .\drop
        run: 7z x win-x86_64-release.zip -y

      - name: Unit Test
        shell: bash
        working-directory: .\drop
        run: |
          set -e
          for exc in ./test/*[^.pdb]; do
            $exc
          done
