name: MacOS Build

on:
  workflow_call:
    inputs:
      config:
        description: 'Build configuration: release or debug'
        type: string
        default: 'release'
      arch:
        description: 'Architecture: arm64 or x86_64'
        type: string
        default: 'arm64'
      cmake_args:
        description: 'Additional CMake arguments'
        type: string
        default: ''
        required: false
    secrets:
      SDK_PASSWORD:
        required: true

jobs:
  osx:
    name: "osx-${{ inputs.arch }}-${{ inputs.config }}"
    runs-on: ${{ inputs.arch == 'x86_64' && 'macos-15-intel' || 'macos-14' }}
    env:
      CONFIG_NAME: "osx-${{ inputs.arch }}-${{ inputs.config }}"
      BUILD_FOLDER: "${{ inputs.config == 'release' && 'RelWithDebInfo' || 'Debug' }}"
    steps:
      - name: Replace problem-causing python installation - https://github.com/TeamForbiddenLLC/warfork-qfusion/pull/325 - Fixed in macos-14
        shell: bash
        run: |
          brew uninstall --force azure-cli aws-sam-cli
          brew install python@3 || brew link --overwrite python@3
          brew install cmake git zip unzip libidn2 curl

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Download steamworks sdk
        run: |
          curl -L https://github.com/Warfork/sdk_internal/raw/refs/heads/main/sdk.zip --output third-party/steamworks/sdk.zip
          unzip -P "$SDK_PASSWORD" third-party/steamworks/sdk.zip -d third-party/steamworks
        env:
          SDK_PASSWORD: ${{ secrets.SDK_PASSWORD }}

      - name: Build
        working-directory: ./source
        run: |
          cmake -B ./build --preset workflow-macos-${{ inputs.config }} ${{ inputs.cmake_args }}
          cd build
          cmake --build . --config ${{ env.BUILD_FOLDER }}

      - name: Package Assets
        working-directory: ./source
        run: cmake --build ./build --target deploy --config ${{ env.BUILD_FOLDER }}
          
      - name: Package warfork
        working-directory: ./source/build/warfork-qfusion
        run: |
          shopt -s nullglob
          tar -czvf ../${{ env.CONFIG_NAME }}.tar.gz ${{ env.BUILD_FOLDER }}/*.app ${{ env.BUILD_FOLDER }}/*.dSYM

      - name: Upload warfork artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.CONFIG_NAME }}
          path: source/build/${{ env.CONFIG_NAME }}.tar.gz
